import { MenuItemTypes } from "~/types";
import { TbAdjustments, TbCheckbox, TbHome, TbLogout, TbPackage, TbStar, TbUser } from "react-icons/tb";
import { logoutUserHandle, setSettingMenuHandle } from "~/utils/storeHandle";

export const MENU: MenuItemTypes[] = [
  {
    key: "anasayfa",
    label: "Ana Sayfa",
    icon: <TbHome className="icon" />,
    url: "/",
  },
  {
    key: "profile",
    label: "Profil",
    icon: <TbUser className="icon" />,
    className: "d-none d-lg-vertical-flex",
    children: [
      // {
      //   key: "profil",
      //   label: "Profil",
      //   icon: <TbUser className="icon" />,
      //   url: "/profile",
      //   parentKey: "profile",
      // },
      // {
      //   key: "settings",
      //   label: "Ayarlar",
      //   icon: <TbSettings className="icon" />,
      //   url: "/settings",
      //   parentKey: "profile",
      // },
      {
        key: "settings",
        label: "Tema Ayarları",
        icon: <TbAdjustments className="icon" />,
        onClick: () => setSettingMenuHandle(true),
        parentKey: "profile",
      },
      {
        key: "logout",
        label: "Çıkış Yap",
        icon: <TbLogout className="icon" />,
        onClick: () => logoutUserHandle(),
        parentKey: "profile",
      },
    ],
  },
];

export const UIMENU: MenuItemTypes[] = [
  {
    key: "home",
    label: "Home",
    icon: <TbHome className="icon" />,
    url: "/ui",
    end: true,
  },
  {
    key: "interface",
    label: "Interface",
    icon: <TbPackage className="icon" />,
    children: [
      {
        key: "alerts",
        label: "Alerts",
        url: "/ui/alerts",
        parentKey: "interface",
      },
      {
        key: "accordion",
        label: "Accordion",
        url: "/ui/accordion",
        parentKey: "interface",
      },
      {
        key: "authentication",
        label: "Authentication",
        parentKey: "interface",
        children: [
          {
            key: "signin",
            label: "Sign in",
            url: "/ui/auth/signin",
            parentKey: "authentication",
          },
          {
            key: "signinlink",
            label: "Sign In link",
            url: "/ui/auth/signinlink",
            parentKey: "authentication",
          },
          {
            key: "signinwithillustration",
            label: "Sign in with illustration",
            url: "/ui/auth/signinwithillustration",
            parentKey: "authentication",
          },
          {
            key: "signinwithcover",
            label: "Sign in with cover",
            url: "/ui/auth/signinwithcover",
            parentKey: "authentication",
          },
          {
            key: "signup",
            label: "Sign up",
            url: "/ui/auth/signup",
            parentKey: "authentication",
          },
          {
            key: "forgotpassword",
            label: "Forgot password",
            url: "/ui/auth/forgotpassword",
            parentKey: "authentication",
          },
          {
            key: "termsofservice",
            label: "Terms of service",
            url: "/ui/auth/termsofservice",
            parentKey: "authentication",
          },
          {
            key: "lockscreen",
            label: "Lock screen",
            url: "/ui/auth/lockscreen",
            parentKey: "authentication",
          },
          {
            key: "twostepverification",
            label: "2 step verification",
            url: "/ui/auth/twostepverification",
            parentKey: "authentication",
          },
          {
            key: "twostepverificationcode",
            label: "2 step verification code",
            url: "/ui/auth/twostepverificationcode",
            parentKey: "authentication",
          },
        ],
      },
      {
        key: "blankpage",
        label: "Blank page",
        url: "/ui/blankpage",
        parentKey: "interface",
      },
      {
        key: "badges",
        label: "Badges",
        url: "/ui/badges",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "buttons",
        label: "Buttons",
        url: "/ui/buttons",
        parentKey: "interface",
      },
      {
        key: "cards",
        label: "Cards",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
        children: [
          {
            key: "samplecards",
            label: "Sample cards",
            url: "/ui/samplecards",
            parentKey: "cards",
          },
          {
            key: "cardactions",
            label: "Card actions",
            url: "/ui/cardactions",
            parentKey: "cards",
            badge: {
              text: "New",
              variant: "success",
            },
          },
          {
            key: "cardsmasonry",
            label: "Cards Masonry",
            url: "/ui/cardsmasonry",
            parentKey: "cards",
          },
        ],
      },
      {
        key: "carousel",
        label: "Carousel",
        url: "/ui/carousel",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "charts",
        label: "Charts",
        url: "/ui/charts",
        parentKey: "interface",
      },
      {
        key: "colors",
        label: "Colors",
        url: "/ui/colors",
        parentKey: "interface",
      },
      {
        key: "colorpicker",
        label: "Color picker",
        url: "/ui/colorpicker",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "datagrid",
        label: "Datagrid",
        url: "/ui/datagrid",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "datatables",
        label: "Datatables",
        url: "/ui/datatables",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "dropdowns",
        label: "Dropdowns",
        url: "/ui/dropdowns",
        parentKey: "interface",
      },
      {
        key: "dropzone",
        label: "Dropzone",
        url: "/ui/dropzone",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "errorpages",
        label: "Error pages",
        parentKey: "interface",
        children: [
          {
            key: "page404",
            label: "404 page",
            url: "/ui/errorpages/page404",
            parentKey: "errorpages",
          },
          {
            key: "page500",
            label: "500 page",
            url: "/ui/errorpages/page500",
            parentKey: "errorpages",
          },
          {
            key: "maintenancepage",
            label: "Maintenance page",
            url: "/ui/errorpages/maintenancepage",
            parentKey: "errorpages",
          },
        ],
      },
      {
        key: "flags",
        label: "Flags",
        url: "/ui/flags",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "inlineplayer",
        label: "Inline player",
        url: "/ui/inlineplayer",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "lightbox",
        label: "Light box",
        url: "/ui/lightbox",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "lists",
        label: "Lists",
        url: "/ui/lists",
        parentKey: "interface",
      },
      {
        key: "modal",
        label: "Modal",
        url: "/ui/modal",
        parentKey: "interface",
      },
      {
        key: "map",
        label: "Map",
        url: "/ui/map",
        parentKey: "interface",
      },
      {
        key: "mapfullsize",
        label: "Map fullsize",
        url: "/ui/mapfullsize",
        parentKey: "interface",
      },
      {
        key: "mapvector",
        label: "Map vector",
        url: "/ui/mapvector",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "markdown",
        label: "Markdown",
        url: "/ui/markdown",
        parentKey: "interface",
      },
      {
        key: "navigation",
        label: "Navigation",
        url: "/ui/navigation",
        parentKey: "interface",
      },
      {
        key: "offcanvas",
        label: "Offcanvas",
        url: "/ui/offcanvas",
        parentKey: "interface",
      },
      {
        key: "pagination",
        label: "Pagination",
        url: "/ui/pagination",
        parentKey: "interface",
      },
      {
        key: "placeholder",
        label: "Placeholder",
        url: "/ui/placeholder",
        parentKey: "interface",
      },
      {
        key: "steps",
        label: "Steps",
        url: "/ui/steps",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "starsrating",
        label: "Stars rating",
        url: "/ui/starsrating",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "tabs",
        label: "Tabs",
        url: "/ui/tabs",
        parentKey: "interface",
      },
      {
        key: "tags",
        label: "Tags",
        url: "/ui/tags",
        parentKey: "interface",
      },
      {
        key: "tables",
        label: "Tables",
        url: "/ui/tables",
        parentKey: "interface",
      },
      {
        key: "typography",
        label: "Typography",
        url: "/ui/typography",
        parentKey: "interface",
      },
      {
        key: "tinymce",
        label: "TinyMCE",
        url: "/ui/tinymce",
        parentKey: "interface",
        badge: {
          text: "New",
          variant: "success",
        },
      },
    ],
  },
  {
    key: "formelements",
    label: "Form Elements",
    icon: <TbCheckbox className="icon" />,
    url: "/ui/formelements",
  },
  {
    key: "extra",
    label: "Extra",
    icon: <TbStar className="icon" />,
    children: [
      {
        key: "emptypage",
        label: "Empty page",
        url: "/ui/emptypage",
        parentKey: "extra",
      },
      {
        key: "cookiebanner",
        label: "Cookie banner",
        url: "/ui/cookiebanner",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "chat",
        label: "Chat",
        url: "/ui/chat",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "activity",
        label: "Activity",
        url: "/ui/activity",
        parentKey: "extra",
      },
      {
        key: "gallery",
        label: "Gallery",
        url: "/ui/gallery",
        parentKey: "extra",
      },
      {
        key: "invoice",
        label: "Invoice",
        url: "/ui/invoice",
        parentKey: "extra",
      },
      {
        key: "searchresults",
        label: "Search results",
        url: "/ui/searchresults",
        parentKey: "extra",
      },
      {
        key: "pricingcards",
        label: "Pricing cards",
        url: "/ui/pricingcards",
        parentKey: "extra",
      },
      {
        key: "pricingtable",
        label: "Pricing table",
        url: "/ui/pricingtable",
        parentKey: "extra",
      },
      {
        key: "faq",
        label: "FAQ",
        url: "/ui/faq",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "users",
        label: "Users",
        url: "/ui/users",
        parentKey: "extra",
      },
      {
        key: "license",
        label: "License",
        url: "/ui/license",
        parentKey: "extra",
      },
      {
        key: "logs",
        label: "Logs",
        url: "/ui/logs",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "music",
        label: "Music",
        url: "/ui/music",
        parentKey: "extra",
      },
      {
        key: "photogrid",
        label: "Photogrid",
        url: "/ui/photogrid",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "tasks",
        label: "Tasks",
        url: "/ui/tasks",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "uptimemonitor",
        label: "Uptime monitor",
        url: "/ui/uptimemonitor",
        parentKey: "extra",
      },
      {
        key: "widgets",
        label: "Widgets",
        url: "/ui/widgets",
        parentKey: "extra",
      },
      {
        key: "wizard",
        label: "Wizard",
        url: "/ui/extrapages/wizard",
        parentKey: "extra",
      },
      {
        key: "settings",
        label: "Settings",
        url: "/ui/settings",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "trialended",
        label: "Trial ended",
        url: "/ui/extrapages/trialended",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "joblisting",
        label: "Job listing",
        url: "/ui/joblisting",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
      {
        key: "pageloader",
        label: "Page loader",
        url: "/ui/extrapages/pageloader",
        parentKey: "extra",
        badge: {
          text: "New",
          variant: "success",
        },
      },
    ],
  },
  {
    key: "profile",
    label: "Profil",
    icon: <TbUser className="icon" />,
    className: "d-none d-lg-vertical-flex",
    children: [
      // {
      //   key: "profil",
      //   label: "Profil",
      //   icon: <TbUser className="icon" />,
      //   url: "/profile",
      //   parentKey: "profile",
      // },
      // {
      //   key: "settings",
      //   label: "Ayarlar",
      //   icon: <TbSettings className="icon" />,
      //   url: "/settings",
      //   parentKey: "profile",
      // },
      {
        key: "settings",
        label: "Tema Ayarları",
        icon: <TbAdjustments className="icon" />,
        onClick: () => setSettingMenuHandle(true),
        parentKey: "profile",
      },
      {
        key: "logout",
        label: "Çıkış Yap",
        icon: <TbLogout className="icon" />,
        onClick: () => logoutUserHandle(),
        parentKey: "profile",
      },
    ],
  },
];
